package br.com.fean.poo2.locadora.modelo.reserva;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0




import br.com.fean.poo2.locadora.modelo.socio.Socio;
import br.com.fean.poo2.locadora.modelo.midia.Midia;
import br.com.fean.poo2.locadora.modelo.dependente.Dependente;
import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer id;
     private Dependente dependentes;
     private Midia midias;
     private Socio socios;
     private Date data2;
     private Date hora;

    public Reserva() {
    }

	
    public Reserva(Dependente dependentes, Midia midias, Socio socios) {
        this.dependentes = dependentes;
        this.midias = midias;
        this.socios = socios;
    }
    public Reserva(Dependente dependentes, Midia midias, Socio socios, Date data2, Date hora) {
       this.dependentes = dependentes;
       this.midias = midias;
       this.socios = socios;
       this.data2 = data2;
       this.hora = hora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dependente getDependentes() {
        return this.dependentes;
    }
    
    public void setDependentes(Dependente dependentes) {
        this.dependentes = dependentes;
    }
    public Midia getMidias() {
        return this.midias;
    }
    
    public void setMidias(Midia midias) {
        this.midias = midias;
    }
    public Socio getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socio socios) {
        this.socios = socios;
    }
    public Date getData2() {
        return this.data2;
    }
    
    public void setData2(Date data2) {
        this.data2 = data2;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


