package br.com.fean.poo2.locadora.modelo.locacao;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0




import br.com.fean.poo2.locadora.modelo.socio.Socio;
import br.com.fean.poo2.locadora.modelo.funcionario.Funcionario;
import br.com.fean.poo2.locadora.modelo.dependente.Dependente;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Locacao generated by hbm2java
 */
public class Locacao  implements java.io.Serializable {


     private Integer id;
     private Dependente dependentes;
     private Funcionario funcionarios;
     private Socio socios;
     private Date data2;
     private Date hora;
     private Double valortotal;
     private Set locacaoMidias = new HashSet(0);

    public Locacao() {
    }

	
    public Locacao(Dependente dependentes, Funcionario funcionarios, Socio socios) {
        this.dependentes = dependentes;
        this.funcionarios = funcionarios;
        this.socios = socios;
    }
    public Locacao(Dependente dependentes, Funcionario funcionarios, Socio socios, Date data2, Date hora, Double valortotal, Set locacaoMidias) {
       this.dependentes = dependentes;
       this.funcionarios = funcionarios;
       this.socios = socios;
       this.data2 = data2;
       this.hora = hora;
       this.valortotal = valortotal;
       this.locacaoMidias = locacaoMidias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dependente getDependentes() {
        return this.dependentes;
    }
    
    public void setDependentes(Dependente dependentes) {
        this.dependentes = dependentes;
    }
    public Funcionario getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionario funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Socio getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socio socios) {
        this.socios = socios;
    }
    public Date getData2() {
        return this.data2;
    }
    
    public void setData2(Date data2) {
        this.data2 = data2;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Double getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(Double valortotal) {
        this.valortotal = valortotal;
    }
    public Set getLocacaoMidias() {
        return this.locacaoMidias;
    }
    
    public void setLocacaoMidias(Set locacaoMidias) {
        this.locacaoMidias = locacaoMidias;
    }




}


