package br.com.fean.poo2.locadora.modelo.funcionario;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Funcionario generated by hbm2java
 * 
 */
@Entity
@Table(name = "funcionario")

public class Funcionario  implements java.io.Serializable {
        @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;
        
    @Column(name = "nome")
    private String nome;
  
    @Column(name = "fone")
    private String fone;
    
    @Column(name = "usuario")
    private String usuario;
    
    @Column(name = "senha")
    private String senha;


   
     private Set devolucaos = new HashSet(0);
     private Set locacaos = new HashSet(0);

    public Funcionario() {
    }

    public Funcionario(String nome, String fone, String usuario, String senha, Set devolucaos, Set locacaos) {
       this.nome = nome;
       this.fone = fone;
       this.usuario = usuario;
       this.senha = senha;
       this.devolucaos = devolucaos;
       this.locacaos = locacaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getDevolucaos() {
        return this.devolucaos;
    }
    
    public void setDevolucaos(Set devolucaos) {
        this.devolucaos = devolucaos;
    }
    public Set getLocacaos() {
        return this.locacaos;
    }
    
    public void setLocacaos(Set locacaos) {
        this.locacaos = locacaos;
    }




}


