package br.com.fean.poo2.locadora.modelo.categoria;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

    private Integer id;
    private String nome;
    private Set tituloses = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nome, Set tituloses) {
        this.nome = nome;
        this.tituloses = tituloses;
    }

    @Override
    public String toString() {
        return this.getNome();
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Set getTituloses() {
        return this.tituloses;
    }

    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }

}
