package br.com.fean.poo2.locadora.modelo.tipomidia;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0


import br.com.fean.poo2.locadora.modelo.midia.Midia;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoMidia generated by hbm2java
 */
public class TipoMidia  implements java.io.Serializable {
     private Integer id;
     private String nome;
     private Set<Midia> midiases = new HashSet(0);

    public TipoMidia() {
    }

    /*
    public TipoMidia(String nome, Set midiases) {
       this.nome = nome;
       this.midiases = midiases;
    }*/
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getMidiases() {
        return this.midiases;
    }
    
    public void setMidiases(Set midiases) {
        this.midiases = midiases;
    }

}


