package br.com.fean.poo2.locadora.modelo.dependente;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0




import br.com.fean.poo2.locadora.modelo.socio.Socio;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dependente generated by hbm2java
 */
public class Dependente  implements java.io.Serializable {


     private Integer id;
     private Socio socios;
     private String nome;
     private Integer sexo;
     private Date datanascimento;
     private String inscricao;
     private Set locacaos = new HashSet(0);
     private Set reservases = new HashSet(0);

    public Dependente() {
    }

	
    public Dependente(Socio socios) {
        this.socios = socios;
    }
    public Dependente(Socio socios, String nome, Integer sexo, Date datanascimento, String inscricao, Set locacaos, Set reservases) {
       this.socios = socios;
       this.nome = nome;
       this.sexo = sexo;
       this.datanascimento = datanascimento;
       this.inscricao = inscricao;
       this.locacaos = locacaos;
       this.reservases = reservases;
    }
    
    public Dependente (Integer id, String nome, Integer sexo, Date datanascimento){
       this.id = id;
       this.nome = nome;
       this.sexo = sexo;
       this.datanascimento = datanascimento;
        
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Socio getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socio socios) {
        this.socios = socios;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }
    public String getInscricao() {
        return this.inscricao;
    }
    
    public void setInscricao(String inscricao) {
        this.inscricao = inscricao;
    }
    public Set getLocacaos() {
        return this.locacaos;
    }
    
    public void setLocacaos(Set locacaos) {
        this.locacaos = locacaos;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


