package br.com.fean.poo2.locadora.modelo.devolucao;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0




import br.com.fean.poo2.locadora.modelo.funcionario.Funcionario;
import br.com.fean.poo2.locadora.modelo.locacaomidia.LocacaoMidia;
import java.util.Date;

/**
 * Devolucao generated by hbm2java
 */
public class Devolucao  implements java.io.Serializable {


     private DevolucaoId id;
     private Funcionario funcionarios;
     private LocacaoMidia locacaoMidia;
     private Date data2;
     private Date hora;
     private Integer diasAtraso;
     private Double multa;
     private Double desconto;
     private Double valor;

    public Devolucao() {
    }

	
    public Devolucao(DevolucaoId id, Funcionario funcionarios, LocacaoMidia locacaoMidia) {
        this.id = id;
        this.funcionarios = funcionarios;
        this.locacaoMidia = locacaoMidia;
    }
    public Devolucao(DevolucaoId id, Funcionario funcionarios, LocacaoMidia locacaoMidia, Date data2, Date hora, Integer diasAtraso, Double multa, Double desconto, Double valor) {
       this.id = id;
       this.funcionarios = funcionarios;
       this.locacaoMidia = locacaoMidia;
       this.data2 = data2;
       this.hora = hora;
       this.diasAtraso = diasAtraso;
       this.multa = multa;
       this.desconto = desconto;
       this.valor = valor;
    }
   
    public DevolucaoId getId() {
        return this.id;
    }
    
    public void setId(DevolucaoId id) {
        this.id = id;
    }
    public Funcionario getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionario funcionarios) {
        this.funcionarios = funcionarios;
    }
    public LocacaoMidia getLocacaoMidia() {
        return this.locacaoMidia;
    }
    
    public void setLocacaoMidia(LocacaoMidia locacaoMidia) {
        this.locacaoMidia = locacaoMidia;
    }
    public Date getData2() {
        return this.data2;
    }
    
    public void setData2(Date data2) {
        this.data2 = data2;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Integer getDiasAtraso() {
        return this.diasAtraso;
    }
    
    public void setDiasAtraso(Integer diasAtraso) {
        this.diasAtraso = diasAtraso;
    }
    public Double getMulta() {
        return this.multa;
    }
    
    public void setMulta(Double multa) {
        this.multa = multa;
    }
    public Double getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(Double desconto) {
        this.desconto = desconto;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }




}


