package br.com.fean.poo2.locadora.modelo.midia;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0




import br.com.fean.poo2.locadora.modelo.tipomidia.TipoMidia;
import br.com.fean.poo2.locadora.modelo.titulo.Titulo;
import br.com.fean.poo2.locadora.modelo.distribuidor.Distribuidor;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Midia generated by hbm2java
 */
public class Midia  implements java.io.Serializable {


     private Integer id;
     private Titulo titulos;
     private TipoMidia tipoMidias;
     private Distribuidor distribuidores;
     private Integer situacao;
     private Date dataaquisicao;
     private String nrserie;
     private Set locacaoMidias = new HashSet(0);
     private Set reservases = new HashSet(0);

    public Midia() {
    }

	
    public Midia(Titulo titulos, TipoMidia tipoMidias, Distribuidor distribuidores) {
        this.titulos = titulos;
        this.tipoMidias = tipoMidias;
        this.distribuidores = distribuidores;
    }
    public Midia(Titulo titulos, TipoMidia tipoMidias, Distribuidor distribuidores, Integer situacao, Date dataaquisicao, String nrserie, Set locacaoMidias, Set reservases) {
       this.titulos = titulos;
       this.tipoMidias = tipoMidias;
       this.distribuidores = distribuidores;
       this.situacao = situacao;
       this.dataaquisicao = dataaquisicao;
       this.nrserie = nrserie;
       this.locacaoMidias = locacaoMidias;
       this.reservases = reservases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Titulo getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Titulo titulos) {
        this.titulos = titulos;
    }
    public TipoMidia getTipoMidias() {
        return this.tipoMidias;
    }
    
    public void setTipoMidias(TipoMidia tipoMidias) {
        this.tipoMidias = tipoMidias;
    }
    public Distribuidor getDistribuidores() {
        return this.distribuidores;
    }
    
    public void setDistribuidores(Distribuidor distribuidores) {
        this.distribuidores = distribuidores;
    }
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }
    public Date getDataaquisicao() {
        return this.dataaquisicao;
    }
    
    public void setDataaquisicao(Date dataaquisicao) {
        this.dataaquisicao = dataaquisicao;
    }
    public String getNrserie() {
        return this.nrserie;
    }
    
    public void setNrserie(String nrserie) {
        this.nrserie = nrserie;
    }
    public Set getLocacaoMidias() {
        return this.locacaoMidias;
    }
    
    public void setLocacaoMidias(Set locacaoMidias) {
        this.locacaoMidias = locacaoMidias;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


