package br.com.fean.poo2.locadora.modelo.classe;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name = "classe")

public class Classe implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "nome")
    private String nome;

    @Column(name = "valor")
    private double valor;

    private Integer diasdevolucao;
    private Set tituloses = new HashSet(0);

    public Classe() {
    }

    public Classe(String nome, Double valor, Integer diasdevolucao, Set tituloses) {
        this.nome = nome;
        this.valor = valor;
        this.diasdevolucao = diasdevolucao;
        this.tituloses = tituloses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Integer getDiasdevolucao() {
        return this.diasdevolucao;
    }

    public void setDiasdevolucao(Integer diasdevolucao) {
        this.diasdevolucao = diasdevolucao;
    }

    public Set getTituloses() {
        return this.tituloses;
    }

    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }

}
