package br.com.fean.poo2.locadora.modelo.distribuidor;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Distribuidor generated by hbm2java
 */
public class Distribuidor  implements java.io.Serializable {


     private Integer id;
     private String razaoSocial;
     private String cnpj;
     private String endereco;
     private String fone;
     private String pessoaContato;
     private Set midiases = new HashSet(0);

    public Distribuidor() {
    }

    public Distribuidor(String razaoSocial, String cnpj, String endereco, String fone, String pessoaContato, Set midiases) {
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.endereco = endereco;
       this.fone = fone;
       this.pessoaContato = pessoaContato;
       this.midiases = midiases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getFone() {
        return this.fone;
    }
    
    public void setFone(String fone) {
        this.fone = fone;
    }
    public String getPessoaContato() {
        return this.pessoaContato;
    }
    
    public void setPessoaContato(String pessoaContato) {
        this.pessoaContato = pessoaContato;
    }
    public Set getMidiases() {
        return this.midiases;
    }
    
    public void setMidiases(Set midiases) {
        this.midiases = midiases;
    }

    @Override
    public String toString() {
        return this.razaoSocial;
    }




}


