package br.com.fean.poo2.locadora.modelo.socio;
// Generated 19/06/2014 18:08:01 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String endereco;
     private String foneRes;
     private String localTrabalho;
     private String foneCom;
     private Integer sexo;
     private String cpf;
     private Date datanascimento;
     private Integer tipo;
     private String inscricao;
     private Set reservases = new HashSet(0);
     private Set locacaos = new HashSet(0);
     private Set dependenteses = new HashSet(0);

    public Socio() {
    }

    public Socio(String nome, String endereco, String foneRes, String localTrabalho, String foneCom, Integer sexo, String cpf, Date datanascimento, Integer tipo, String inscricao, Set reservases, Set locacaos, Set dependenteses) {
       this.nome = nome;
       this.endereco = endereco;
       this.foneRes = foneRes;
       this.localTrabalho = localTrabalho;
       this.foneCom = foneCom;
       this.sexo = sexo;
       this.cpf = cpf;
       this.datanascimento = datanascimento;
       this.tipo = tipo;
       this.inscricao = inscricao;
       this.reservases = reservases;
       this.locacaos = locacaos;
       this.dependenteses = dependenteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getFoneRes() {
        return this.foneRes;
    }
    
    public void setFoneRes(String foneRes) {
        this.foneRes = foneRes;
    }
    public String getLocalTrabalho() {
        return this.localTrabalho;
    }
    
    public void setLocalTrabalho(String localTrabalho) {
        this.localTrabalho = localTrabalho;
    }
    public String getFoneCom() {
        return this.foneCom;
    }
    
    public void setFoneCom(String foneCom) {
        this.foneCom = foneCom;
    }
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getInscricao() {
        return this.inscricao;
    }
    
    public void setInscricao(String inscricao) {
        this.inscricao = inscricao;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }
    public Set getLocacaos() {
        return this.locacaos;
    }
    
    public void setLocacaos(Set locacaos) {
        this.locacaos = locacaos;
    }
    public Set getDependenteses() {
        return this.dependenteses;
    }
    
    public void setDependenteses(Set dependenteses) {
        this.dependenteses = dependenteses;
    }




}


